version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_container
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: db
    ports:
      - "8085:8085"
    depends_on: 
      db:
        condition: service_healthy
    networks:
      - thaym-network

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      # MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./cmd/migrate/migrations:/docker-entrypoint-initdb.d/  
    networks:
      - thaym-network
    ports:
      - "3306:3306"  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]     
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:

networks:
  thaym-network:
      driver: bridge
